FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime

#RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install --no-cache opencv-contrib-python-headless onnx onnxruntime-gpu==1.19 matplotlib timm albumentations

# Create working directory
WORKDIR /home/workspace/



