FROM nvcr.io/nvidia/pytorch:24.10-py3

#RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install --no-cache onnx onnxruntime-gpu==1.19 matplotlib timm albumentations

# Create working directory
WORKDIR /home/workspace/



