FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

#RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install --no-cache opencv-contrib-python-headless onnx onnxruntime-gpu==1.18 matplotlib timm albumentations

# Create working directory
WORKDIR /home/workspace/



